### PR TITLE
issue #13 - Add not-found page

### PR DESCRIPTION
**Pull request by VBsaini**
Added a not found page

image

- Vaibhav Saini

### CODE REVIEW

**Comment by VBsaini** [comment]
@sergomen can you please review the PR

**Comment by sergomen** [comment]
> @sergomen can you please review the PR

Hey @VBsaini. You need to transform CSS style in not-found.module.css into TailwindCSS, because in this project we use TailwindCSS library. Check the [official docs](https://tailwindcss.com/docs/installation).

**Review by VBsaini — COMMENTED** [review]
changed normal css to tailwind css

**Comment by sergomen** [comment]
Ok, @VBsaini , thanks!

**Pull request merged**
